version: "3.8"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: ahmed
      MYSQL_PASSWORD: admin
    ports:
      - 3308:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mailer:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025